name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Push to dokku
      uses: dokku/github-action@v1.4.0
      with:
        branch: main
        git_remote_url: ssh://dokku@${{ secrets.DOKKU_HOST }}:22/trusty-tail
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}